# Spring Boot 应用配置
spring:
  application:
    name: CourseSelectionSystem

  # Spring Boot配置
  main:
    allow-circular-references: true

  # 数据源配置
  datasource:
    url: jdbc:mysql://localhost:3306/courseselectionsystem?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

  # JSP视图解析器配置
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
    static-path-pattern: /static/**

  # 静态资源配置
  web:
    resources:
      static-locations: classpath:/static/

  # 文件上传配置
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

  # Redis配置
  data:
    redis:
      host: localhost
      port: 6379
      password: # 如果有密码请填写
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 20
          max-wait: -1ms
          max-idle: 10
          min-idle: 0

  # ActiveMQ配置 - 连接外部ActiveMQ服务器
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    in-memory: false
    pool:
      enabled: true
      max-connections: 50
      idle-timeout: 30s

  # JMS配置
  jms:
    template:
      default-destination: course.selection.queue
      delivery-mode: persistent
      priority: 100
      qos-enabled: true
      receive-timeout: 1000ms
      time-to-live: 36000000ms

# 服务器配置
server:
  port: 8080
  servlet:
    context-path: /CourseSelectionSystem_war
    session:
      # 禁用会话持久化存储，避免反序列化问题
      persistent: false
      # 设置会话超时时间（30分钟）
      timeout: 30m
      # 设置会话存储类型为内存
      store-type: none
  # Tomcat配置
  tomcat:
    # 基础目录设置
    basedir: target/tomcat
    # 临时文件处理
    threads:
      max: 200
      min-spare: 10
    # 连接器配置
    connection-timeout: 20000ms
    max-swallow-size: 100MB
    # 临时文件清理
    accesslog:
      enabled: false
    # 额外资源清理配置
    resource:
      cache-ttl: 20000
  error:
    whitelabel:
      enabled: false
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
    include-exception: true

# MyBatis配置
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    lazy-loading-enabled: true
    aggressive-lazy-loading: false

# 日志配置
logging:
  level:
    root: info
    liu:
      dao: debug
      mapper: debug
    com:
      alibaba:
        druid: debug

# 文件上传配置
file:
  upload-dir: uploads